INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'CLASSICA', 1);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'TORINO', 2);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11, 'CAMPIONE supplément cheddar', 3);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (13, 'PAYSANNE supplément salami, bacon', 4);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'NAPOLI', 5);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'ORIENTALE', 6);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11, 'CALABRIA supplément romarin', 7);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (12.50, 'TEXAS supplément champignons tranchés, tomates faîches', 8);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'FAJITAS', 9);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'CAPRI', 10);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11.50, 'MEXICAINE supplément anchois', 11);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11, 'SAN PETRO supplément poivrons', 12);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11.50, '4 FROMAGES supplément salami', 13);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'CHARCUTIERE', 14);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'ROMA (4 SAISONS)', 15);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11, 'SICILIENNE supplément oignons rouges', 16);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'PAVAROTTI', 17);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10.50, 'RACLETTE supplément olives', 18);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'PALERMA', 19);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11.50, 'BOURSIN supplément boursin', 20);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (13.50, 'CLASSICA supplément boursin, oeuf', 1);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'TORINO', 2);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'CAMPIONE', 3);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'PAYSANNE', 4);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (12, 'NAPOLI supplément maïs', 5);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'ORIENTALE', 6);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (12, 'CALABRIA courgettes', 7);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'TEXAS', 8);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'FAJITAS', 9);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'CAPRI', 10);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11.50, 'PAYSANNE supplément tomates séchées', 4);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11, 'SAN PETRO supplément basilic frais', 12);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, '4 FROMAGES', 13);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'CHARCUTIERE', 14);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11.50, 'CLASSICA supplément bacon', 1);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'SICILIENNE', 16);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11, 'PAVAROTTI supplément cheddar', 17);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'PAYSANNE', 4);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (12, 'PALERMA supplément oeuf', 19);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'BOURSIN', 20);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'CLASSICA',1);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11.50, 'TORINO supplément anchois', 2);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11.50, 'CAMPIONE supplément salami', 3);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'PAYSANNE', 4);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'NAPOLI', 5);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'ORIENTALE', 6);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11, 'CALABRIA supplément oignons rouges', 7);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'TEXAS', 8);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'FAJITAS', 9);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (12, 'CAPRI supplément courgettes', 10);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'MEXICAINE', 11);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11, 'SAN PETRO supplément origan séché', 12);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, '4 FROMAGES', 13);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'CHARCUTIERE', 14);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10.50, "ROMA (4 SAISONS) supplément huile d'olive extra vierge", 15);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'SICILIENNE', 16);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'PAVAROTTI', 17);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (12, 'RACLETTE supplément champignons marinés', 18);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'PALERMA', 19);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11, 'BOURSIN supplément poivrons', 20);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'CLASSICA',1);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11.50, 'TORINO supplément anchois', 2);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11.50, 'CAMPIONE supplément salami', 3);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'PAYSANNE', 4);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'NAPOLI', 5);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'ORIENTALE', 6);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11, 'CALABRIA supplément oignons rouges', 7);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'TEXAS', 8);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'FAJITAS', 9);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (12, 'CAPRI supplément courgettes', 10);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'MEXICAINE', 11);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11, 'SAN PETRO supplément origan séché', 12);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, '4 FROMAGES', 13);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'CHARCUTIERE', 14);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10.50, "ROMA (4 SAISONS) supplément huile d'olive extra vierge", 15);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'SICILIENNE', 16);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'PAVAROTTI', 17);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (12, 'RACLETTE supplément champignons marinés', 18);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'PALERMA', 19);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11, 'BOURSIN supplément poivrons', 20);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'CLASSICA',1);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11.50, 'TORINO supplément anchois', 2);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11.50, 'CAMPIONE supplément salami', 3);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'PAYSANNE', 4);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'NAPOLI', 5);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'ORIENTALE', 6);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11, 'CALABRIA supplément oignons rouges', 7);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'TEXAS', 8);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'FAJITAS', 9);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (12, 'CAPRI supplément courgettes', 10);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'MEXICAINE', 11);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11, 'SAN PETRO supplément origan séché', 12);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, '4 FROMAGES', 13);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'CHARCUTIERE', 14);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10.50, "ROMA (4 SAISONS) supplément huile d'olive extra vierge", 15);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'SICILIENNE', 16);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'PAVAROTTI', 17);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (12, 'RACLETTE supplément champignons marinés', 18);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'PALERMA', 19);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11, 'BOURSIN supplément poivrons', 20);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'CLASSICA', 1);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'TORINO', 2);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11, 'CAMPIONE supplément cheddar', 3);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (13, 'PAYSANNE supplément salami, bacon', 4);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'NAPOLI', 5);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'ORIENTALE', 6);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11, 'CALABRIA supplément romarin', 7);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (12.50, 'TEXAS supplément champignons tranchés, tomates faîches', 8);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'FAJITAS', 9);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'CAPRI', 10);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11.50, 'MEXICAINE supplément anchois', 11);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11, 'SAN PETRO supplément poivrons', 12);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11.50, '4 FROMAGES supplément salami', 13);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'CHARCUTIERE', 14);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'ROMA (4 SAISONS)', 15);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11, 'SICILIENNE supplément oignons rouges', 16);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'PAVAROTTI', 17);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10.50, 'RACLETTE supplément olives', 18);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'PALERMA', 19);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11.50, 'BOURSIN supplément boursin', 20);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'CAPRI', 10);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11.50, 'MEXICAINE supplément anchois', 11);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11, 'SAN PETRO supplément poivrons', 12);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11.50, '4 FROMAGES supplément salami', 13);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'CHARCUTIERE', 14);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'ROMA (4 SAISONS)', 15);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11, 'SICILIENNE supplément oignons rouges', 16);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'PAVAROTTI', 17);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10.50, 'RACLETTE supplément olives', 18);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'PALERMA', 19);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11.50, 'BOURSIN supplément boursin', 20);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (13.50, 'CLASSICA supplément boursin, oeuf', 1);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'TORINO', 2);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'CAMPIONE', 3);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'PAYSANNE', 4);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (12, 'NAPOLI supplément maïs', 5);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'ORIENTALE', 6);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (12, 'CALABRIA courgettes', 7);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'TEXAS', 8);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'FAJITAS', 9);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'CAPRI', 10);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11.50, 'PAYSANNE supplément tomates séchées', 4);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11, 'SAN PETRO supplément basilic frais', 12);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, '4 FROMAGES', 13);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'CHARCUTIERE', 14);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11.50, 'CLASSICA supplément bacon', 1);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'SICILIENNE', 16);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11, 'PAVAROTTI supplément cheddar', 17);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'PAYSANNE', 4);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (12, 'PALERMA supplément oeuf', 19);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'BOURSIN', 20);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'CLASSICA',1);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11.50, 'TORINO supplément anchois', 2);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11.50, 'CAMPIONE supplément salami', 3);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'PAYSANNE', 4);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'NAPOLI', 5);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'ORIENTALE', 6);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11, 'CALABRIA supplément oignons rouges', 7);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'TEXAS', 8);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'FAJITAS', 9);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (12, 'CAPRI supplément courgettes', 10);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'MEXICAINE', 11);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11, 'SAN PETRO supplément origan séché', 12);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, '4 FROMAGES', 13);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'CHARCUTIERE', 14);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10.50, "ROMA (4 SAISONS) supplément huile d'olive extra vierge", 15);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'SICILIENNE', 16);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'PAVAROTTI', 17);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (12, 'RACLETTE supplément champignons marinés', 18);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'PALERMA', 19);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11, 'BOURSIN supplément poivrons', 20);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'CLASSICA',1);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11.50, 'TORINO supplément anchois', 2);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11.50, 'CAMPIONE supplément salami', 3);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'PAYSANNE', 4);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'NAPOLI', 5);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'ORIENTALE', 6);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11, 'CALABRIA supplément oignons rouges', 7);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'TEXAS', 8);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'FAJITAS', 9);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'CHARCUTIERE', 14);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'ROMA (4 SAISONS)', 15);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11, 'SICILIENNE supplément oignons rouges', 16);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'PAVAROTTI', 17);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10.50, 'RACLETTE supplément olives', 18);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'PALERMA', 19);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11.50, 'BOURSIN supplément boursin', 20);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'CAPRI', 10);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11.50, 'MEXICAINE supplément anchois', 11);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11, 'SAN PETRO supplément poivrons', 12);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11.50, '4 FROMAGES supplément salami', 13);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'CHARCUTIERE', 14);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'ROMA (4 SAISONS)', 15);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11, 'SICILIENNE supplément oignons rouges', 16);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'PAVAROTTI', 17);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10.50, 'RACLETTE supplément olives', 18);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'PALERMA', 19);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (11.50, 'BOURSIN supplément boursin', 20);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (13.50, 'CLASSICA supplément boursin, oeuf', 1);
INSERT INTO PizzaFinale (PrixFinal, DescriptionPizzaFinale, ID_Pizza) VALUES (10, 'TORINO', 2);