INSERT INTO RecettePizza (NomPizza, DescriptionPizza, PrixBasePizza) VALUES ('CLASSICA', 'Pâte à pizza, Sauce tomate, Mozzarella, Jambon, Basilic', 10);
INSERT INTO RecettePizza (NomPizza, DescriptionPizza, PrixBasePizza) VALUES ('TORINO', 'Pâte à pizza, Sauce tomate, Mozzarella, Jambon, Champignons', 10);
INSERT INTO RecettePizza (NomPizza, DescriptionPizza, PrixBasePizza) VALUES ('CAMPIONE', 'Pâte à pizza, Crème Fraîche, Mozzarella, Pepperoni, Poivrons', 10);
INSERT INTO RecettePizza (NomPizza, DescriptionPizza, PrixBasePizza) VALUES ('PAYSANNE', 'Pâte à pizza, Crème Fraîche, Tomates, Mozzarella, Oignons, Champignons, Poivrons', 10);
INSERT INTO RecettePizza (NomPizza, DescriptionPizza, PrixBasePizza) VALUES ('NAPOLI', 'Pâte à pizza, Sauce tomate, Mozzarella, Anchois, Olives', 10);
INSERT INTO RecettePizza (NomPizza, DescriptionPizza, PrixBasePizza) VALUES ('ORIENTALE', 'Pâte à pizza, Sauce tomate, Mozzarella, Poulet, Poivrons, Oignons', 10);
INSERT INTO RecettePizza (NomPizza, DescriptionPizza, PrixBasePizza) VALUES ('CALABRIA', 'Pâte à pizza, Sauce tomate, Mozzarella, Oeuf, Oignons, Olives', 10);
INSERT INTO RecettePizza (NomPizza, DescriptionPizza, PrixBasePizza) VALUES ('TEXAS', 'Pâte à pizza, Crème Fraîche, Sauce barbecue, Mozzarella, Poulet, Oignons, Poivrons', 10);
INSERT INTO RecettePizza (NomPizza, DescriptionPizza, PrixBasePizza) VALUES ('FAJITAS', 'Pâte à pizza, Crème Fraîche, Mozzarella, Boeuf haché, Poivrons, Oignons', 10);
INSERT INTO RecettePizza (NomPizza, DescriptionPizza, PrixBasePizza) VALUES ('CAPRI', 'Pâte à pizza, Sauce tomate, Mozzarella, Jambon de Parme, Roquette, Parmesan', 10);
INSERT INTO RecettePizza (NomPizza, DescriptionPizza, PrixBasePizza) VALUES ('MEXICAINE', 'Pâte à pizza, Sauce tomate, Mozzarella, Chorizo, Maïs, Piments', 10);
INSERT INTO RecettePizza (NomPizza, DescriptionPizza, PrixBasePizza) VALUES ('SAN PETRO', 'Pâte à pizza, Crème Fraîche, Tomates, Mozzarella, Crevettes, Romarin', 10);
INSERT INTO RecettePizza (NomPizza, DescriptionPizza, PrixBasePizza) VALUES ('4 FROMAGES', 'Pâte à pizza, Sauce tomate, Mozzarella, Gorgonzola, Chèvre, Parmesan', 10);
INSERT INTO RecettePizza (NomPizza, DescriptionPizza, PrixBasePizza) VALUES ('CHARCUTIERE', 'Pâte à pizza, Crème Fraîche, Tomates, Mozzarella, Jambon, Bacon, Saucisse italienne, Pepperoni', 10);
INSERT INTO RecettePizza (NomPizza, DescriptionPizza, PrixBasePizza) VALUES ('ROMA (4 SAISONS)', 'Pâte à pizza, Crème Fraîche, Tomates, Mozzarella, Jambon, Champignons, Olives, Artichauts', 10);
INSERT INTO RecettePizza (NomPizza, DescriptionPizza, PrixBasePizza) VALUES ('SICILIENNE', 'Pâte à pizza, Crème Fraîche, Tomates, Mozzarella, Aubergines grillées, Ricotta, Basilic', 10);
INSERT INTO RecettePizza (NomPizza, DescriptionPizza, PrixBasePizza) VALUES ('PAVAROTTI', 'Pâte à pizza, Sauce tomate, Mozzarella, Champignons, Aubergines grillées, Courgettes, Roquette', 10);
INSERT INTO RecettePizza (NomPizza, DescriptionPizza, PrixBasePizza) VALUES ('RACLETTE', 'Pâte à pizza, Crème Fraîche, Mozzarella, Pommes de terre, Bacon, Oignons', 10);
INSERT INTO RecettePizza (NomPizza, DescriptionPizza, PrixBasePizza) VALUES ('PALERMA', 'Pâte à pizza, Sauce tomate, Mozzarella, Salami, Tomates, Roquette', 10);
INSERT INTO RecettePizza (NomPizza, DescriptionPizza, PrixBasePizza) VALUES ('BOURSIN', 'Pâte à pizza, Sauce tomate, Mozzarella, Poulet, Champignons, Boursin', 10);