insert into SupplementPizza (NomSupplementPizza, PrixSupplementPizza, ID_Ingredient) values ('Supplément cheddar', 1, 8);
insert into SupplementPizza (NomSupplementPizza, PrixSupplementPizza, ID_Ingredient) values ('Supplément champignons tranchés', 1, 13);
insert into SupplementPizza (NomSupplementPizza, PrixSupplementPizza, ID_Ingredient) values ('Supplément poivrons', 1, 14);
insert into SupplementPizza (NomSupplementPizza, PrixSupplementPizza, ID_Ingredient) values ('Supplément oignons rouges', 1, 15);
insert into SupplementPizza (NomSupplementPizza, PrixSupplementPizza, ID_Ingredient) values ('Supplément olives', 0.50, 16);
insert into SupplementPizza (NomSupplementPizza, PrixSupplementPizza, ID_Ingredient) values ('Supplément tomates fraîches', 1.50, 17);
insert into SupplementPizza (NomSupplementPizza, PrixSupplementPizza, ID_Ingredient) values ('Supplément aubergines grillées', 1, 20);
insert into SupplementPizza (NomSupplementPizza, PrixSupplementPizza, ID_Ingredient) values ('Supplément courgettes', 2, 21);
insert into SupplementPizza (NomSupplementPizza, PrixSupplementPizza, ID_Ingredient) values ('Supplément bacon', 1.50, 29);
insert into SupplementPizza (NomSupplementPizza, PrixSupplementPizza, ID_Ingredient) values ('Supplément salami', 1.50, 30);
insert into SupplementPizza (NomSupplementPizza, PrixSupplementPizza, ID_Ingredient) values ('Supplément anchois', 1.50, 31);
insert into SupplementPizza (NomSupplementPizza, PrixSupplementPizza, ID_Ingredient) values ('Supplément piments', 1.50, 33);
insert into SupplementPizza (NomSupplementPizza, PrixSupplementPizza, ID_Ingredient) values ('Supplément origan séché', 1, 34);
insert into SupplementPizza (NomSupplementPizza, PrixSupplementPizza, ID_Ingredient) values ('Supplément basilic frais', 1, 35);
insert into SupplementPizza (NomSupplementPizza, PrixSupplementPizza, ID_Ingredient) values ('Supplément romarin', 1, 36);
insert into SupplementPizza (NomSupplementPizza, PrixSupplementPizza, ID_Ingredient) values ("Supplément huile d'olive extra vierge", 0.50, 37);
insert into SupplementPizza (NomSupplementPizza, PrixSupplementPizza, ID_Ingredient) values ('Supplément champignons marinés', 2, 41);
insert into SupplementPizza (NomSupplementPizza, PrixSupplementPizza, ID_Ingredient) values ('Supplément tomates séchées', 1.50, 42);
insert into SupplementPizza (NomSupplementPizza, PrixSupplementPizza, ID_Ingredient) values ('Supplément roquette', 1, 44);
insert into SupplementPizza (NomSupplementPizza, PrixSupplementPizza, ID_Ingredient) values ('Supplément boursin', 1.50, 12);
insert into SupplementPizza (NomSupplementPizza, PrixSupplementPizza, ID_Ingredient) values ('Supplément maïs', 2, 45);
insert into SupplementPizza (NomSupplementPizza, PrixSupplementPizza, ID_Ingredient) values ('Supplément oeuf', 2, 38);