INSERT INTO Supplement (NomSupplement, PrixSupplement) VALUES ('Tiramisu', 3.00);
INSERT INTO Supplement (NomSupplement, PrixSupplement) VALUES ('Panna Cotta', 2.50);
INSERT INTO Supplement (NomSupplement, PrixSupplement) VALUES ('Cannoli', 2.00);
INSERT INTO Supplement (NomSupplement, PrixSupplement) VALUES ('Tartufo', 2.50);
INSERT INTO Supplement (NomSupplement, PrixSupplement) VALUES ('Affogato', 3.00);
INSERT INTO Supplement (NomSupplement, PrixSupplement) VALUES ('Zeppole', 1.50);
INSERT INTO Supplement (NomSupplement, PrixSupplement) VALUES ('Biscotti', 2.00);
INSERT INTO Supplement (NomSupplement, PrixSupplement) VALUES ('Gelato al Limone', 2.50);
INSERT INTO Supplement (NomSupplement, PrixSupplement) VALUES ('Sfogliatella', 2.00);
INSERT INTO Supplement (NomSupplement, PrixSupplement) VALUES ('Cassata', 3.00);
INSERT INTO Supplement (NomSupplement, PrixSupplement) VALUES ('Coca-Cola', 1.50);
INSERT INTO Supplement (NomSupplement, PrixSupplement) VALUES ('Sprite', 1.50);
INSERT INTO Supplement (NomSupplement, PrixSupplement) VALUES ('Fanta', 1.50);
INSERT INTO Supplement (NomSupplement, PrixSupplement) VALUES ('Eau', 1.50);
INSERT INTO Supplement (NomSupplement, PrixSupplement) VALUES ("Jus d'orange", 1.50);
INSERT INTO Supplement (NomSupplement, PrixSupplement) VALUES ('Ice Tea', 1.50);
INSERT INTO Supplement (NomSupplement, PrixSupplement) VALUES ('Eau pétillante', 1.50);
INSERT INTO Supplement (NomSupplement, PrixSupplement) VALUES ('Fanta citron', 1.50);
INSERT INTO Supplement (NomSupplement, PrixSupplement) VALUES ('Coca-Cola Zero', 1.50);
INSERT INTO Supplement (NomSupplement, PrixSupplement) VALUES ('Coca-Cola Cherry', 1.50);